### PR TITLE
Rerender and bump to 1.3.1

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
This will hopefully supersede #1

**Comment by dpryan79** [comment]
Ah, now I remember, the R 3.5.1 package for Linux never got built when #2 was merged in. Hopefully this will solve that by retriggering things.

**Comment by cbrueffer** [comment]
CircleCI needed a nudge in the ic10trainingdata package; the Linux builds are running now.

**Comment by cbrueffer** [comment]
The missing Linux r3.5 package has been uploaded now; I think this PR can be closed?

**Comment by dpryan79** [comment]
Thanks @cbrueffer !

**Pull request closed without merging**
